name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.18', '1.19' ]
    name: Go ${{ matrix.go }} build
    steps:
      - uses: actions/checkout@master
      - uses: reviewdog/action-golangci-lint@v2
        with:
          fail_on_error: true
          go_version: ${{ matrix.go }}
      - run: |
          gofmt -l . && test -z $(gofmt -l .)
          go vet .
          go install github.com/mgechev/revive@latest
          revive -config revive.toml .
      - run: go build -v .
      - run: go test -v .
