name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: reviewdog/action-golangci-lint@v2
        with:
          fail_on_error: true
      - run: |
          gofmt -l . && test -z $(gofmt -l .)
          go vet -unsafeptr=false .
          go install github.com/mgechev/revive@latest
          revive -config revive.toml .
      - run: go build -v .
      - run: go test -v .
